name: almanac_of_wisdom
description: A place for Wisdom
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  animated_text_kit: ^4.2.2
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.1
  firebase_analytics: ^10.4.5
  flutter_inappwebview: ^5.7.2+3
  iconly: ^1.0.1
  intl: ^0.18.1
  google_fonts: ^6.0.0
  sortedmap: ^0.5.3
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - images/
    - assets/
