name: almanac_of_wisdom
description: Stock Market Daily Blogs and Updates
version: 2.0.0+3

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  animated_text_kit: ^4.2.2
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  firebase_core: ^3.5.0
  firebase_analytics: ^11.3.2
  flutter_inappwebview: ^6.1.0
  google_fonts: ^6.0.0
  iconly: ^1.0.1
  intl: ^0.19.0
  package_info_plus: ^8.0.2
  sortedmap: ^0.5.3
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.0

flutter_launcher_icons:
  android: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - images/
    - assets/icon/
